name: Generate sitemap

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write          # lets the bot push back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cicirello/generate-sitemap@v1
        with:
          path-to-root: .                         # root of your Pages site
          base-url-path: https://stolenaletheia.io
          sitemap-format: xml
          include-pdf: true                       # optional

      - name: Commit sitemap
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sitemap.xml
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "chore: update sitemap [skip ci]"
            git push
          fi
